CREATE TYPE cat_race AS ENUM ('PERSIAN', 'MAINE_COON', 'SIAMESE', 'RAGDOLL', 'BENGAL', 'SPHYNX', 'BRITISH_SHORTHAIR', 'ABYSSINIAN', 'SCOTTISH_FOLD', 'BIRMAN');
CREATE TYPE cat_sex AS ENUM('MALE','FEMALE');

CREATE TABLE IF NOT EXISTS public.cats (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(30) NOT NULL,
    race cat_race NOT NULL,
    sex cat_sex NOT NULL,
    age_in_month INT NOT NULL DEFAULT 1,
    description VARCHAR(200) NOT NULL,
    has_matched BOOLEAN,
    image_urls VARCHAR[] NOT NULL DEFAULT ARRAY[]::VARCHAR[],
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS user_id ON cats (user_id);